default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: 127.0.0.1

development:
  primary:
    <<: *default
    database: db_sample_development
    port: 33061
  primary_replica:
    <<: *default
    database: db_sample_development
    port: 33062
    replica: true
test:
  primary:
    <<: *default
    database: db_sample_test
    port: 33061
  primary_replica:
    <<: *default
    database: db_sample_test
    port: 33062
    replica: true
production:
  primary:
    <<: *default
    database: db_sample_production
    port: 33061
  primary_replica:
    <<: *default
    database: db_sample_production
    port: 33062
    replica: true
